package djf.settings;

/**
 * This enum provides properties that are to be loaded via
 * XML files to be used for setting up the application.
 * 
 * @author Richard McKenna
 * @version 1.0
 */
public enum AppPropertyType {
    // LOADED FROM app_properties.xml

    // INITIAL WINDOW TITLE AND LOGO
    APP_TITLE,
    APP_LOGO,

    // INITIAL WINDOW GEOMETRY
    PREF_WIDTH,
    PREF_HEIGHT,
    START_MAXIMIZED,
    
    // FOR FINDING THE CSS FILE
    APP_CSS,
    APP_PATH_CSS,

    // FILE TOOLBAR ICONS
    NEW_ICON,
    LOAD_ICON,
    SAVE_ICON,
    SAVE_AS_ICON,
    EXPORT_ICON,
    EXIT_ICON,
    REDO_ICON,
    UNDO_ICON,
    ABOUT_ICON,
        
    //First line 
    ADDLINE_ICON,
    REMOVELINE_ICON,
    LISTSTATION_ICON,
    //Second line
    ADDSTATION_ICON,
    REMOVESTATION_ICON,
    ROTATE_ICON,
    
    FINDLOCATION_ICON,
    
    BOLD_ICON,
    ITALICS_ICON,
    ZOOMOUT_ICON,
    ZOOMIN_ICON,
    INCREASE_ICON,
    DECREASE_ICON,

    WELCOMEDIALOG_ICON,
    // FILE TOOLBAR TOOLTIPS FOR BUTTONS
    NEW_TOOLTIP,
    LOAD_TOOLTIP,
    SAVE_TOOLTIP,
    SAVE_AS_TOOLTIP,
    EXPORT_TOOLTIP,
    EXIT_TOOLTIP,
    REDO_TOOLTIP,
    UNDO_TOOLTIP,
    ABOUT_TOOLTIP,
    
    ADDLINE_TOOLTIP,
    REMOVELINE_TOOLTIP,
    LISTSTATION_TOOLTIP,
    
    ADDSTATION_TOOLTIP,
    REMOVESTATION_TOOLTIP,
    ROTATE_TOOLTIP,
    
    FINDLOCATION_TOOLTIP,
    
    BOLD_TOOLTIP,
    ITALICS_TOOLTIP,
    ZOOMOUT_TOOLTIP,
    ZOOMIN_TOOLTIP,
    INCREASE_TOOLTIP,
    DECREASE_TOOLTIP,

    ADDSTATIONTOLINE_TOOLTIP,
    REMOVESTATIONFROMLINE_TOOLTIP,
    // ERROR MESSAGES AND TITLES FOR DIALOG BOXES
    NEW_ERROR_MESSAGE,
    NEW_ERROR_TITLE,
    LOAD_ERROR_MESSAGE,
    LOAD_ERROR_TITLE,
    SAVE_ERROR_MESSAGE,
    SAVE_ERROR_TITLE,
    PROPERTIES_LOAD_ERROR_MESSAGE,
    PROPERTIES_LOAD_ERROR_TITLE,
	
    // AND VERIFICATION MESSAGES AND TITLES
    NEW_COMPLETED_MESSAGE,
    NEW_COMPLETED_TITLE,
    LOAD_COMPLETED_MESSAGE,
    LOAD_COMPLETED_TITLE,
    SAVE_COMPLETED_MESSAGE,
    SAVE_COMPLETED_TITLE,	
    SAVE_UNSAVED_WORK_TITLE,
    SAVE_UNSAVED_WORK_MESSAGE,
    SAVE_WORK_TITLE,
    LOAD_WORK_TITLE,
    
    EXPORT_COMPLETED_MESSAGE,
    EXPORT_COMPLETED_TITLE,
    EXPORT_ERROR_MESSAGE,
    EXPORT_ERROR_TITLE,
    EXPORT_UNSAVED_WORK_MESSAGE,
    EXPORT_UNSAVED_WORK_TITLE,
    EXPORT_WORK_TITLE,

    // DATA FILE EXTENSIONS AND DESSCRIPTIONS
    WORK_FILE_EXT,
    WORK_FILE_EXT_DESC
}
